### ISSUE TITLE
KISS passthrough no longer working with 1.0.65

### ISSUE THREAD

**Issue by bosbefok** [FETtec/ESC-Firmware#1]
I have the 4in1 wired to the kiss v2 fc using the traditional wiring harness. After updating the 4in1 from 1.0.29 to 1.0.65 the KISS passthrough no longer works and the fettec configurator cannot detect the ESCs.

Using kiss-gui  v2.0.16 fettec configurator v0.1.6 on MacOS 10.14.3

**Comment by FETtec** [comment]
Hi, can you keep the FC in passthrough mode (keep the FC connected to your Mac and power-cycle the ESC).

**Comment by bosbefok** [comment]
I gave that a try but it didn't seem to make any difference. I've also tried on a windows PC and behaviour is the same. 

I've not made any changes to the wiring, and passthrough was working fine on 1.0.29.

**Comment by FETtec** [comment]
Okay. What FC firmware you are on. What is the ESC protocol (Dshot2400). Beside the GUI problem does the ESC beep on boot?

**Comment by bosbefok** [comment]
Dshot2400 on KISS v2 R39b. The ~~ESC~~ motor does beep on boot and the red light is on.

**Comment by bosbefok** [comment]
Previously I was running FC passthrough on the new esc (with no motors soldered on yet) and all 4 esc's were showing up fine. I've just soldered on one motor to test, and I actually now see 1 esc showing in the fettec configurator. Was there something in this latest firmware which would prevent the esc from appearing if it didn't have a motor soldered to it?

**Comment by bosbefok** [comment]
To summarize - on 1.0.6 (default) and 1.0.29 all ESCs appear in the configurator without any motors attached. On 1.0.65 only ESCs that have a motor attached appear in the configurator. Not sure if this is intentional.

**Comment by FETtec** [comment]
Yes this was a bug which was missed. 1.0.66 fixes that
