### ISSUE TITLE
3D mode & motor direction settings randomly changing

### ISSUE THREAD

**Issue by Siytek** [FETtec/ESC-Firmware#4]
I just took my Fettec FC + Fettec 45A ESC setup out for the maiden. It flew beautifully, very impressed! However there seems to be a bug with the 3D mode and motor direction settings.

I set up the ESC in the configurator, but both the 3D mode and motor direction settings seem to randomly change to something that I don't want. I have to go back into the configurator, change them back and save it again to temporarily fix it. The quad flies great until the settings randomly change again. Only seems to happen on the ground, perhaps after power cycling.

I am using the latest Fettec FC firmware and DShot 2400. ESC version 1.0.96 with the 45A 30x30 ESC + Spike Absorber

EDIT: I have been out and flown a couple of packs on 1.0.84 and I did not experience the problem. I will stick with the older firmware for now.

**Comment by lichtl** [comment]
Thanks for that detailed report. Will try to replicate this.

**Comment by Siytek** [comment]
No problem. If you cannot replicate then I will try the latest firmware again. Perhaps there was something messed up that was corrected by the re-flashing rather than rolling back to 1.0.84. I have now flown about 20 packs on the older firmware and everything works very nicely!

**Comment by lichtl** [comment]
Hi, sorry for the long waiting but we couldn't replicate it. Have you already moved to the current version or still run on 1.0.84?
