### ISSUE TITLE
Fettec esc, fettec configurator connetion problem

### ISSUE THREAD

**Issue by chumarro** [FETtec/ESC-Firmware#5]
I have kiss v1 fc and fettec 45a esc. although I did all the connections right. There is nothing wrong with the kiss v1 connection, but the fettec configurator connection does not work. "esc not found" warns

**Comment by ethanxy** [comment]
I have the save issue with ESC configurator(Mac) when connected to Fettec 45A esc via Fettec FC

**Comment by lichtl** [comment]
on the V1 you have to use the TX3 pad instead of the TLM pad.
