### ISSUE TITLE
ESC configurator does not work

### ISSUE THREAD

**Issue by ethanxy** [FETtec/ESC-Firmware#6]
45a fettec ESC + fettec FC
Kiss FC passthrough does not work in ESC configurator v0.1.23(Mac)

**Comment by lichtl** [comment]
Could you please specify this. Are you running latest firmware and have wired it correctly?

**Comment by hakrc1** [comment]
你好，我是HAKRC工厂，如何可以合作呢？

**Comment by hakrc1** [comment]
Hello, I am HAKRC factory, how can we cooperate?

**Comment by hakrc1** [comment]
Hello, I am HAKRC factory, how can we cooperate?

**Comment by ethanxy** [comment]
> Hello, I am HAKRC factory, how can we cooperate?

What’s kinds of cooperate ? Do you have a email ?

**Comment by hakrc1** [comment]
This is my email,










欧阳平发
Mob:&nbsp;+86-18664379879
***@***.***
Tel: 0755-84539567
 https://www.hakrc.com
深圳市海科技术有限公司
深圳市坪山区翠景路43号华意隆产业园3栋4楼


 ----------Reply to Message----------
 On Sun, Apr 30, 2023 00:41 AM ***@***.***&gt; wrote:

  

  
Hello, I am HAKRC factory, how can we cooperate?
  
What’s kinds of cooperate ? Do you have a email ?
